<?php

header('Content-Description: File Transfer');
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . $deckdownload_package->getName() . '.apkg"');
header('Expires: 0');
header('Cache-Control: must-revalidate');
header('Pragma: public');
header('Content-Length: ' . filesize('decks/'.$deckdownload_package->getId().'.apkg'));
readfile('decks/'.$deckdownload_package->getId().'.apkg');

