<p>
    Kdykoli nahraješ nový Anki balíček, je uložen pod tvým autorským jménem a „editačním klíčem“.
</p>
<p>
    Aby se ti s tímto systémem pracovalo jednodušeji, můžeš předvyplnit tyto dvě informace na této stránce. Kdykoli
    v budoucnu budeš vytvářet nový balíček, jméno autora a editační klíč budou automaticky nastaveny jako výchozí
    hodnoty. A kdykoli půjdeš na stránku pro správu nahraných balíčků, předvyplněný editační klíč bude automaticky
    použit k přihlášení.
</p>
<p>
    Měj prosím na paměti, že po odeslání formuláře níže <strong>nedojde k odeslání žádných dat na naše servery</strong>.
    Formulář vytvoří pouze <strong>místní „účet“ na tvém zařízení</strong> uložením zvoleného hesla a klíče do lokálního
    úložiště tvého prohlížeče (do něčeho jako cookie). Pokud vymažeš cookies nebo přeinstaluješ svůj prohlížeč, jméno a klíč
    budou ztraceny. Proto si v každém případě své údaje zapamatuj (především klíč) pro případ, že je budeš muset v budoucnosti
    opět muset manuálně zadat.
</p>

<details>
    <summary><h3>Zobrazit formulář (obsahuje tvůj aktuální editační klíč ve viditelné formě!)</h3></summary>
    <form method="POST">
        <p>
            <label for="author-input">Jméno autora: </label><br>
            <input type="text" id="author-input" name="author" value="" maxlength="31" required/><br>
            <small>
                Jméno autora slouží pouze jako důkaz tvých zásluh a umožňuje ostatním jednodušší vyhledávání tvých
                balíčů. Více uživatelů si může zvolit stejné jméno autora, ale není to doporučováno.
            </small>
        </p>
        <p>
            <label for="key-input">Editační klíč: </label><br>
            <input type="text" id="key-input" name="key" value="" maxlength="31" required/>
            <button id="generate-key-button">Vygenerovat</button><br>
            <small>
                Editační klíč je něco jako heslo, které je nutné pro budoucí aktualizování, upravování nebo odstraňování
                balíčků vytvořených pomocí něj. Udržuj svůj editační klíč v tajnosti, kdokoli s přístupem k němu může
                modifikovat tvé balíčky a rozeslat mezi jejich uživatele destruktivní aktualizace. Uvědom si, že klíč
                nemůže být obnoven, pokud je zapomenut, s výjimkou případu kdy se osobně znáš se správcem tohoto webu.<br>
                <strong>Nevol jako editační klíč nic, co už používáš jako heslo někde jinde!</strong>
                Z technických důvodů není editační klíč chráněn šifrováním a ačkoli se snažíme držet ukládaná data v bezpečí,
                nikdy nemůžeme vyloučit hackerský útok a jejich krádež.
            </small>
        </p>
        <p>
            Změna jména autora a editačního klíče zde jej <strong>nezmění</strong> pro balíčky, které jsi v minulosti pomocí
            těchto údajů vytvořil/a. Doporučujeme nejprve aktualizovat tyto údaje u tvých dříve nahraných balíčků
            na stránce <a href="/my-decks" id="manage-link-account">Mé balíčky</a> předtím, než změníš údaje v tomto formuláři
            (pokud tedy nechceš začít budoucí balíčky vydávat pod novou identitou).
        </p>
        <button id="submit-button">Uložit</button>
        <span id="result-box" style="color:green"></span>
    </form>
</details>

