<p>Toto je seznam všech veřejných Anki balíčků nahraných na tento web v této kategorii.</p>
<p>Pro zobrazení více informací o jakémkoli balíčku nebo pro jeho stažení jednoduše klikni na jeho název.</p>
<p>Můžeš rychle vyhledávat mezi balíčky pomocí funkce „Najít“ (<kbd>Ctrl + F</kbd>).</p>
<table class="wide-table striped-table">
    <tr>
        <th class="txt-l">Název balíčku</th>
        <th class="txt-l">Autor</th>
        <th>Verze</th>
        <th>Naposledy aktualizováno</th>
    </tr>
    <?php /** @var array $browse_packages Array of the Package objects, containing information about public decks */
    foreach ($browse_packages as $package) : ?>
        <tr>
            <td class="txt-l">
                <a href="/deck/<?= $package['package_id'] ?>">
                    <?= $package['name'] ?>
                    <?php if ($package['details_link'] !== 'LOCAL') : ?>
                         <img class="icon" src="/public/img/icons/ext-link.svg" alt="(externí odkaz)">
                    <?php endif ?>
                </a>
            </td>
            <td class="txt-l"><?= $package['author'] ?></td>
            <td><?= $package['version'] ?>.<?= $package['minor_version'] ?></td>
            <td><?= $package['updated_at'] ?></td>
        </tr>
    <?php endforeach ?>
</table>

