<p>This is the list of all public Anki decks uploaded to this webserver under this category.</p>
<p>To view more information about any file or to download it, simply click its name.</p>
<p>You can quickly find the deck you need by opening the search tool (<kbd>Ctrl + F</kbd>).</p>
<table class="wide-table striped-table">
    <tr>
        <th class="txt-l">Deck name</th>
        <th class="txt-l">Author</th>
        <th>Version</th>
        <th>Last updated at</th>
    </tr>
    <?php /** @var array $browse_packages Array of the Package objects, containing information about public decks */
    foreach ($browse_packages as $package) : ?>
        <tr>
            <td class="txt-l">
                <a href="/deck/<?= $package['package_id'] ?>">
                    <?= $package['name'] ?>
                    <?php if ($package['details_link'] !== 'LOCAL') : ?>
                         <img class="icon" src="/public/img/icons/ext-link.svg" alt="(external link)">
                    <?php endif ?>
                </a>
            </td>
            <td class="txt-l"><?= $package['author'] ?></td>
            <td><?= $package['version'] ?>.<?= $package['minor_version'] ?></td>
            <td><?= $package['updated_at'] ?></td>
        </tr>
    <?php endforeach ?>
</table>

