<p>Veřejné Anki balíčky nahrávané do této služby jsou kategorizovány podle svého oboru (předmětu).</p>
<p>Nové kategorie jsou přidávány kdykoli je nahrán balíček, který nelze do existujících kategorií zařadit.</p>
<p>
    Kategorie na této stránce jsou řazeny podle počtu nahraných veřejných balíčků, které obsahují (s výjimkou
    kategorie „Nekategorizováno“). Pro rychle nalezení žádané kategorie můžeš využít <kbd>Ctrl + F</kbd>.
</p>
<div class="categories-wrapper">
    <?php foreach ($categories_categories as $category) : ?>
        <?php if ($category['package_count'] === 0) {
            continue;
        } ?>
        <a class="plain-link" href="/browse/<?= $category['category_id'] ?>">
            <div class="category-box"
                 style="background: linear-gradient( rgb(255 255 255 / 62%), rgb(255 255 255 / 62%) ), url('<?= $category['icon']; ?>')">
                <p><strong><?= $category['name'] ?></strong></p>
                <p><?= $category['package_count'] ?>
                    <?=($category['package_count'] > 4) ? ' veřejných balíčků' : ($category['package_count'] > 1) ? 'veřejné balíčky' : 'veřejný balíček' ?></p>
            </div>
        </a>
    <?php endforeach ?>
</div>
<p class="txt-c">
    <small>Je možné, že existuje více kategorií, ale nejsou zde zobrazeny, protože neobsahují žádné veřejné balíčky.</small>
</p>
<p class="txt-c">
    Všechny ikony kategorií pocházejí z <a href="https://openmoji.org/" target="_blank">OpenMoji</a> – projektu ikon a emoji s otevřeným zdrojovým kódem.
    Licence: <a href="https://creativecommons.org/licenses/by-sa/4.0/#">CC BY-SA 4.0</a>
</p>

