<?php if (isset($create_createdId)) : //Form was just submitted with valid data and a package entry has been created?>
<form id="proceed-form" method="POST" action="/upload/<?= $create_createdId ?>">
    <input type="hidden" name="key" value="<?= $create_key ?>"/>
</form>
<script>
    document.getElementById("proceed-form").submit();
</script>
<?php else : ?>
<form method="post" id="edit-form">
    <fieldset>
        <label for="category-input">Kategorie:</label>
        <select name="category" id="category-input" required>
            <?php foreach ($create_categories as $categoryId => $categoryName) : ?>
                <option <?= ($create_category == $categoryId) ? 'selected ' : '' ?>value="<?= $categoryId ?>">
                    <?= $categoryName ?>
                </option>
            <?php endforeach ?>
        </select>
        <small>
            Vyber prosím jednu z kategorií ze seznamu, do které tvůj balíček témticky nejvíce spadá.
            Po rozkliknutí možností je můžeš filtrovat psaním začátku názvu kategorie na klávesnici.
            Pokud není žádná taková kategorie k dispizici, nastav možnost „Nekategorizováno“ a správce
            webu buďto vytvoří pro tvůj balíček novou kategorii, nebo jej zařadí do nějaké existující sám.
        </small>
    </fieldset>
    <fieldset>
        <label for="deck-name-input">Název balíčku:</label>
        <input type="text" name="deck-name" id="deck-name-input" maxlength="122"
               placeholder="Eponyma v ortopedii" value="<?= $create_deckName ?? '' ?>" required/>
        <small>
            Tvůj balíček bude mít tento název poté, co si jej uživatelé stáhnout.
            <strong>Nezahrnuj do názvu balíčku příponu <code>.apkg</code>.</strong>
        </small>
    </fieldset>
    <fieldset>
        <label for="author-input">Autor (předvyplněno ze tvého <a href="/account">nastavení účtu</a>):</label>
        <input type="text" name="author" id="author-input" value="<?= $create_author ?? '' ?>" maxlength="31"
               required/>
        <small>Toto jméno bude zobrazeno vedle názvu balíčku. Můžeš vyplnit i něco jako „Anonym“.</small>
    </fieldset>
    <fieldset>
        <label for="public-input">Ponechat balíček veřejný?</label>
        <input type="checkbox" name="public" id="public-input"
               <?php if (($create_public ?? true) !== false) : ?>checked<?php endif ?>/>
        <small>Doporučujeme ponechat všechny balíčky jako veřejné – tobě to neuškodí a ostatním to může pomoci.</small>
        <small>
            Pro soukromé balíčky bude vygenrován přístupový kód, který bude obsažen ve sdílecím odkazu, jenž bude
            zpočátku známý pouze tobě. Pouze uživatelé, se kterými tento odkaz nasdílíš budou moci takový balíček
            stáhnout a balíček nebude uveden na <a href="/browse">stránce se seznamem balíčků</a>.<br>
            <strong>Varování:</strong> Balíček vytvořený jako veřejný nemůže být později zesoukroměn!
        </small>
    </fieldset>
    <fieldset>
        <label for="new-key-input">Editační klíč (předvyplněno ze tvého <a href="/account">nastavení účtu</a>):</label>
        <input type="password" name="key" id="key-input" maxlength="31" value="<?= $create_key ?? '' ?>" required/>
        <small>
            Editační klíč je něco jako heslo, které je nutné pro budoucí aktualizování, upravování nebo odstraňování
            balíčků vytvořených pomocí něj. Udržuj svůj editační klíč v tajnosti, kdokoli s přístupem k němu může
            modifikovat tvé balíčky a rozeslat mezi jejich uživatele destruktivní aktualizace. Uvědom si, že klíč
            nemůže být obnoven, pokud je zapomenut, s výjimkou případu kdy se osobně znáš se správcem tohoto webu.<br>
            Očekává se, že použiješ stejný editační klíč pro všechny své balíčky, aby se ti se naším systémem pracovalo
            jednodušeji. Měl/a by jsi proto zajistit, že tebou zvolený klíč bude dostatečně silný.<br>
            <strong>Nevol jako editační klíč nic, co už používáš jako heslo někde jinde!</strong>
            Z technických důvodů není editační klíč chráněn šifrováním a ačkoli se snažíme držet ukládaná data v bezpečí,
            nikdy nemůžeme vyloučit hackerský útok a jejich krádež.
        </small>
    </fieldset>
    <fieldset>
        <button id="submit-button">Pokračovat</button>
        <div style="color: red">
            <?= $create_error ?? '' ?>
        </div>
    </fieldset>
</form>
<?php endif ?>
