<?php if (isset($deck_uploadAction)) : ?>
    <div style="border: 1px solid black; background-color:lightskyblue; padding: 8px;">
        <p><strong>Package has successfully been <?= $deck_uploadAction ?>.</strong></p>
        <p>Time to share it with others, just send them the following link:<br><code style="white-space: normal; background-color: #ddd; color: #222; padding: 4px;"><?= $deck_downloadLink ?></code></p>
        <?php if ($deck_uploadAction === 'updated') : ?>
            <p>
                All users that use the previous (or any older) version of your deck will now see an update notification
                when they open it to study.
            </p>
        <?php endif ?>
        <?php if (!empty($deck_accessKey)) : ?>
            <p>
                Your Anki package is set as private. This means that it won't be listed on the
                <a href="/browse">Deck List webpage</a> and only users using a link with the access code will be able
                to download the package.
            </p>
            <p>The access code is contained in the link above, so be careful with whom you share it.</p>
        <?php endif ?>
    </div>
<?php endif ?>
<p>To download new version of this Anki deck, click the button below.</p>
<p>After downloading, just import the new package to your Anki client. None of your cards or planning will be
    overwritten. Anki will simply check which of your cards were changed in this version and updates their
    content.</p>
<p>
    File name: <code><?= $deck_package->getName() ?>.apkg</code><br>
    File size: <code><?= number_format(filesize('decks/'.$deck_packageId.'.apkg') / 1000000, 2) ?> MB</code><br>
    Version number: <code><?= $deck_package->getVersion() ?></code><br>
    File updated at: <code><?= $deck_package->getUpdatedDate()->format('Y-m-d H:i:s'); ?></code>
</p>
<button style="display: block; background-color:limegreen; font-size: x-large;">
    <a style="color: inherit; text-decoration: none;"
       href="/deck/<?= $deck_packageId ?>/download<?php if (!empty($deck_accessKey)) : ?>?key=<?= $deck_accessKey ?><?php endif ?>">
        Download the file
    </a>
</button>
<h2>If you're updating an existing deck and not importing this one for the first time:</h2>
<p>After importing the new file, replace the description of the deck with the following code to reset the update status for the new version.</p>
<pre style="white-space: normal; padding: 4px; background-color: black; color: white;"><code>&lt;div style="margin: 30px auto; left: 0; right: 0; border: 3px solid black; border-radius: 5px; text-align: center; width: fit-content; padding: 15px;"&gt;&lt;h2&gt;Update check&lt;/h2&gt;&lt;h6&gt;This might not work on other than desktop versions of Anki.&lt;/h6&gt;&lt;a href="http://<?= $_SERVER['SERVER_NAME'] ?>/update<?= $deck_queryString ?>"&gt;&lt;img src="http://<?= $_SERVER['SERVER_NAME'] ?>/check-update<?= $deck_queryString ?>" alt="Update check failed. Check your internet connection or try again later." /&gt;&lt;/a&gt;&lt;/div&gt;</code></pre>
<p>You need to do this, because updating your current deck will not overwrite the deck description, which holds the current version of your deck (the yellow numbers in the code above). Without updating the description, your Anki will still think you're using the outdated version.</p>

