<?php if (isset($deck_uploadAction)) : ?>
    <div style="border: 1px solid black; background-color:lightskyblue; padding: 8px;">
        <p><strong>Balíček byl úspěšně <?= $deck_uploadAction ?>.</strong></p>
        <p>Je načase sdílet jej s ostatními, stačí jím poslat následující odkaz:<br><code style="white-space: normal; background-color: #ddd; color: #222; padding: 4px;"><?= $deck_shareLink ?></code></p>
        <?php if ($deck_uploadAction === 'prolinkován') : ?>
            <p>
                Pokud chceš obejít přesměrování, můžeš také prostě sdílet odkaz, který jsi zadával/a v předchozím kroku.
                Takový postup ale obejde i nutnost znalosti přístupového kódu, pokudj is balíček nenastavil/a jako veřejný.
            </p>
        <?php elseif ($deck_uploadAction === 'aktualizován') : ?>
            <p>
                Všichni uživatelé předchozí (nebo jakékoli starší) verze tvého balíčku nyní uvidí výzvu k aktualizaci,
                až balíček otevřou.
            </p>
        <?php elseif ($deck_uploadAction === 'upraven') : ?>
        <p>
            Uživatelé předchozí verze <b>neuvidí výzvu k aktualizaci</b>, protože jsi označil tuto aktualizaci jako malou (<i>patch</i>).
        </p>
        <?php endif ?>
        <?php if (!empty($deck_accessKey)) : ?>
            <p>
                Tvůj Anki balíček je nastaven jako soukromý. To znamená, že nebude uveden
                na <a href="/browse">stránce se seznamem balíčků</a> a pouze uživatelé s odkazem obsahujíím
                přístupový kód jej budou moci stáhnout.
            </p>
            <p>Přístupový kód je obsažen v odkazu výše, proto buď opatrný/á, s kým jej budeš sdílet.</p>
        <?php endif ?>
    </div>
<?php endif ?>

<?php if ($deck_uploadAction === 'prolinkován') : ?>
    <p>Po kliknutí na název tohoto balíčku v seznamu balíčků budou uživatelé předměrování na:</p>
    <a href="<?= $deck_detailsLink ?>"><?= $deck_detailsLink ?></a>
<?php else : ?>
    <p>Pro stažení nejnovější verze tohoto Anki balíčku klikni na tlačítko níže.</p>
    <p>
        Po dokončení stahování stačí naimportovat stažený soubor do tvého Anki klienta.
        Žádné tvé poznámky nebo pokrok nebude přepsán, Anki jednoduše porovná, které poznámky
        byly v této verzi změněny a aktualizuje jejich obsah.
    </p>
    <p>
        Název souboru: <code><?= $deck_package->getName() ?>.apkg</code><br>
        <?php if (file_exists('decks/'.$deck_packageId.'.apkg')) : ?>
            Velikost souboru: <code><?= number_format(filesize('decks/'.$deck_packageId.'.apkg') / 1000000, 2) ?> MB</code><br>
        <?php endif ?>
        Verze: <code><?= $deck_package->getFullVersion() ?></code><br>
        Soubor aktualizován: <code><?= $deck_package->getUpdatedDate()->format('Y-m-d H:i:s'); ?></code>
    </p>
    <?php if ($deck_hostedLocally): ?>
        <button style="display: block; background-color:limegreen; font-size: x-large;">
            <a style="color: inherit; text-decoration: none;"
               href="<?= $deck_downloadLink ?>">
                Stáhnout balíček
            </a>
        </button>
    <?php else: ?>
        <button style="display: block; background-color:dodgerblue; font-size: x-large;">
            <a style="color: inherit; text-decoration: none;"
               href="<?= $deck_downloadLink ?>">
                Stáhnout balíček
            </a>
        </button>
        <small>(ze serveru třetí strany)</small><br>
    <?php endif ?>
    <small>Stažením tohoto Anki balíčku souhlasíš s našimi jednoduchými <a href="/terms-of-service">podmínkami služby</a>.</small>
    <h2>Pokud svůj balíček aktualizuješ a neimportuješ jej porpvé:</h2>
    <p>Po importu staženého souboru nahraď popisek balíčku kódem níže pro aktualizaci čísla nainstalované verze.</p>
    <pre style="white-space: normal; padding: 4px; background-color: black; color: white;"><code>&lt;div style="margin: 30px auto; left: 0; right: 0; border: 3px solid black; text-align: center; width: fit-content; padding: 15px; color: black; background-color: white;"&gt;&lt;h2&gt;Kontrola aktualizací&lt;/h2&gt;&lt;h6&gt;Toto nemusí fungovat na jiných, než desktopových verzích Anki.&lt;/h6&gt;&lt;a href="http://<?= $_SERVER['SERVER_NAME'] ?>/update<?= $deck_queryString ?>"&gt;&lt;img src="http://<?= $_SERVER['SERVER_NAME'] ?>/check-update<?= $deck_queryString ?>" alt="Kontrola aktualizací selhala. Zkontroluj své internetové připojení a zkus to znovu později." /&gt;&lt;/a&gt;&lt;/div&gt;</code></pre>
    <p>Toto musíš udělat, protože aktualizace existujícího balíčku někdy nepřepíše jeho popisek, který obsahuje informaci o nainstalované verze (žluté číslo v kódu výše). Bez aktualizace popisku si tvůj Anki klient bude stále myslet, že používáš zastaralou verzi balíčku.</p>
<?php endif ?>

