<p>Balíček s  ID <?= $deleted_packageId ?> byl úspěšně odstraněn z naší služby.</p>
<p>Následující URL adresy budou nyní navracet chybový kód 410 (Zaniklo):</p>
<ul>
    <li><a style="color: #d33;" href="/deck/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/deck/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/deck/<?= $deleted_packageId ?>/download">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/deck/<?= $deleted_packageId ?>/download</a></li>
    <li><a style="color: #d33;" href="/upload/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/upload/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/patch/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/patch/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/uploaded/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/uploaded/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/updated/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/updated/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/stats/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/stats/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/stats/<?= $deleted_packageId ?>/full">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/stats/<?= $deleted_packageId ?>/full</a></li>
    <li><a style="color: #d33;" href="/edit/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/edit/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/delete/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/delete/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/check-update/<?= $deleted_packageId ?>/0">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/check-update/<?= $deleted_packageId ?>/*</a></li>
    <li><a style="color: #d33;" href="/update/<?= $deleted_packageId ?>/0">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/update/<?= $deleted_packageId ?>/*</a></li>
</ul>
<p>Všechny detaily o tomto balíčku, kromě jeho ID byly vymazány z naší databáze.</p>
<p>Soubor <code>.apkg</code> který jsi pravděpodobně v minulosti nahrál/a byl rovněž odstraněn.</p>

