<p>Jsi si jistý, že chceš odstranit <strong><?= $delete_deckName ?></strong>?</p>
<p>Ujisti se, že jsi si vědom/a následků:</p>
<ul>
    <li>
		Všichni uživatelé tohoto balíčku uvidí v jeho popisku oznámení, že jejich balíček nebyl v naší databázi nalezen
		a že byl nejspíše odstraněn svým autorem.
    </li>
    <li>
		Stránka pro aktualizaci balíčku bude nahrazena chybovou stránkou "410 – Zaniklo". Všechny odkazy na stránku balíčku
		na našem webu budou rovněž odebrány.
    </li>
    <li>
		Pokud se rozhodneš tento balíček v budoucnost opět nahrát, bude mít jiné ID než původní balíček
		a uživatelé původního balíčku nezačnou potenciální výzvy k aktualizaci znovu dostávat.
    </li>
    <li>
		Anki balíček bude trvale odstraněn z našich serverů (pokud jsi ho na naše servery nahrál) a ani my jej
		nebudeme schopni obnovit, pokud ztratíš svojí zálohu.
    </li>
    <li>
		Metadata tohoto balíčku (název, autor, verze, odkaz ke stažení, editační klíč, u neveřejných balíčků ještě přístupový klíč)
		budou rovněž z naší databáze vymazány.
    </li>
    <li>
		Veškeré statistiky o míře používání tohoto balíčku budou také vymazány.
    </li>
    <li>
		Jediná informace, která zůstane o tomto balíčku na našich serverech zachována bude jeho ID, poznámka že byl smazán
		a časové razítko, kdy k jeho smazání došlo.
    </li>
</ul>
<form method="POST">
    <fieldset>
        <p>
			Pokud jsi si jistý/á že rozumíš důsledkům, vyplň prosím editační klíč pro tento balíček pro potvrzení
			a klikni na tlačítko.
        </p>
        <input type="hidden" name="key" value="<?= $delete_key ?>" required/>
        <input type="password" name="confirm-key" maxlength="31" required/>
        <input type="submit" value="Trvale odstranit tento balíček"/>
        <div style="color: red">
            <?= $delete_error ?? '' ?>
        </div>
    </fieldset>
</form>
