<p>Package with ID <?= $deleted_packageId ?> was successfully deleted from our service.</p>
<p>The following URLs will now return the 410 (Gone) response code:</p>
<ul>
    <li><a style="color: #d33;" href="/deck/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/deck/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/deck/<?= $deleted_packageId ?>/download">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/deck/<?= $deleted_packageId ?>/download</a></li>
    <li><a style="color: #d33;" href="/upload/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/upload/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/patch/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/patch/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/uploaded/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/uploaded/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/updated/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/updated/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/stats/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/stats/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/stats/<?= $deleted_packageId ?>/full">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/stats/<?= $deleted_packageId ?>/full</a></li>
    <li><a style="color: #d33;" href="/edit/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/edit/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/delete/<?= $deleted_packageId ?>">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/delete/<?= $deleted_packageId ?></a></li>
    <li><a style="color: #d33;" href="/check-update/<?= $deleted_packageId ?>/0">http(s)://<?= $_SERVER['SERVER_NAME'] ?>/delete/<?= $deleted_packageId ?>/*</a></li>
</ul>
<p>All details about this package, aside from its ID were deleted from our database.</p>
<p>The <code>.apkg</code> file you previously uploaded was deleted from our server as well.</p>

