<form method="post" id="edit-form">
    <input type="hidden" name="key" id="key-input" value="<?= $edit_key ?>"/> <!-- Value will be filled in by JavaScript -->
    <fieldset>
        <label for="category-input">Kategorie:</label>
        <select name="category" id="category-input" required>
            <?php foreach ($edit_categories as $categoryId => $categoryName) : ?>
                <option <?= ($edit_category == $categoryId) ? 'selected ' : '' ?>value="<?= $categoryId ?>">
                    <?= $categoryName ?>
                </option>
            <?php endforeach ?>
        </select>
        <small>
            Vyber prosím jednu z kategorií ze seznamu, do které tvůj balíček témticky nejvíce spadá.
            Po rozkliknutí možností je můžeš filtrovat psaním začátku názvu kategorie na klávesnici.
            Pokud není žádná taková kategorie k dispizici, nastav možnost „Nekategorizováno“ a správce
            webu buďto vytvoří pro tvůj balíček novou kategorii, nebo jej zařadí do nějaké existující sám.
        </small>
    </fieldset>
    <fieldset>
        <label for="deck-name-input">Název balíčku:</label>
        <input type="text" name="deck-name" id="deck-name-input" maxlength="122"
               placeholder="Eponyma v ortopedii" value="<?= $edit_deckName ?? '' ?>" required/>
    </fieldset>
    <fieldset>
        <label for="author-input">Autor (předvyplněno ze tvého <a href="/account">nastavení účtu</a>):</label>
        <input type="text" name="author" id="author-input" value="<?= $edit_author ?? '' ?>" maxlength="31" required/>
    </fieldset>
    <?php if (!$edit_public) : ?>
        <fieldset>
            <label for="public-input">Publikovat balíček</label>
            <input type="checkbox" name="public" id="public-input"/>
            <small>
                Tvůj balíček byl vytvořen jako soukromý, což znamená že není uveden mezi ostatními na <a href="/browse">
                stránce se seznamem balíčků</a> a pouze uživatelé s původním odkazem (obsahujícím přístupový kód) jej
                mohou zobrazit a stáhnout.<br>
                Můžeš odstranit nutnost znalosti přístupového kódu publikováním balíčku, takže kdokoli s přístupem
                k internetu si bude moci balíček prohlédnout a stáhnout. Všichni současní uživatelé soukromé verze
                balíčku jej budou moci nadále používat, jako by se nic nezměnilo.<br>
                <strong>Varování:</strong> Publikovaný balíček nemůže být v budoucnu znovu zesoukroměn!
            </small>
        </fieldset>
    <?php endif ?>
    <fieldset>
        <label for="new-key-input">Editační klíč (předvyplněno ze tvého <a href="/account">nastavení účtu</a>):</label>
        <input type="password" name="new-key" id="new-key-input" maxlength="31" value="<?= $edit_newKey ?>" required/> <!-- Value will be filled in by JavaScript -->
        <small>
            Očekává se, že použiješ stejný editační klíč pro všechny své balíčky, aby se ti se naším systémem pracovalo
            jednodušeji. Měl/a by jsi proto zajistit, že tebou zvolený klíč bude dostatečně silný.<br>
            <strong>Nevol jako editační klíč nic, co už používáš jako heslo někde jinde!</strong>
            Z technických důvodů není editační klíč chráněn šifrováním a ačkoli se snažíme držet ukládaná data v bezpečí,
            nikdy nemůžeme vyloučit hackerský útok a jejich krádež.
        </small>
    </fieldset>
    <fieldset>
        <button id="submit-button">Uložit</button>
        <div style="color: red">
            <?php foreach ($edit_errors as $error) : ?>
                <span><?= $error ?></span><br>
            <?php endforeach ?>
        </div>
        <div style="color: green">
            <?php foreach ($edit_saves as $saves) : ?>
                <span><?= $saves ?></span><br>
            <?php endforeach ?>
        </div>
    </fieldset>
</form>

