<p>Vítejte na webu pro sdílení medických Anki balíčků.</p>
<p>Tento web byl naprogramován medikem z 2. LF a je určen pro všechny studenty všech lékařských fakult.</p>
<p>Web je open-source, kód je k dispozici na GitHubu (<a target="_blank" href="https://github.com/ShadyMedic/Anki-Deck-Update-Checker">zde</a>). Pokud najdete chybu nebo máte nějaký návrh na vylepšení, <a href="https://github.com/ShadyMedic/Anki-Deck-Update-Checker/issues" target="_blank">vytvořte prosím hlášení</a>.
<p>Použijte odkazy v horní části stránky pro navigaci po webu.</p>
<p style="text-align: center; margin-top: 5em;">
    Pomohl ti tento web? Budu rád za jakýkoli symbolický příspěvek na provoz.
    <br><br>
    <a href="https://liberapay.com/ShadyMedic/donate"><img alt="Donate using Liberapay" src="https://exams.shadysoft.eu/public/img/liberapay.svg" class="donate-btn"></a>
    <br><br>
    <small style="font-size: 0.75em;">
        Tímto podpoříš mě jako vývojáře tohoto webu, <b>ne tvůrce zde umístněných Anki balíčků</b> (byť velkou část z nich jsem také dělal já).<br>
        Darované peníze zatím ani nepokrývají náklady na provoz tohoto serveru, takže svým příspěvkem mi pomáháš minimalizovat ztráty.<br>
        Mockrát děkuji.
    </small>
</p>
