<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php foreach (self::$cssFiles as $cssFile) : ?>
        <link rel="stylesheet" href="/public/css/<?= $cssFile ?>.css">
    <?php endforeach ?>
    <title>Anki Package Update Checker</title>
</head>
<body data-page-id="<?=
    /** @var string $layout_page_id ID of the generated webpage, initialized in the specific controller */
    $layout_page_id
?>">
<nav>
    <ul>
        <li><a href="/">Homepage</a></li>
        <li><a href="/browse">Public Decks</a></li>
        <li><a href="/my-decks">My Decks</a></li>
        <li><a href="/new-deck">Upload a New Deck</a></li>
    </ul>
</nav>
<main>
    <header>
        <h1><?=
            /** @var string $layout_title Title of the webpage, initialized in the specific controller */
            $layout_title
        ?></h1>
    </header>
    <article>
        <?php require self::VIEWS_DIRECTORY.'/'.array_shift(self::$views).'.phtml'; ?>
    </article>
</main>
<?php foreach (self::$jsFiles as $jsFile) : ?>
    <script type="text/javascript" src="/public/js/<?= $jsFile ?>.js"></script>
<?php endforeach ?>
</body>
</html>

