<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php foreach (self::$cssFiles as $cssFile) : ?>
        <link rel="stylesheet" href="/public/css/<?= $cssFile ?>.css">
    <?php endforeach ?>
    <title>Anki Package Update Checker</title>
</head>
<body data-page-id="<?=
    /** @var string $layout_page_id ID of the generated webpage, initialized in the specific controller */
    $layout_page_id
?>">
<nav>
    <span class="nav-row">
        <span id="home-link" class="nav-item">Homepage</span>
        <span id="browse-link" class="nav-item">Public&nbsp;Decks</span>
    </span>
    <span class="nav-row">
        <span id="manage-link" class="nav-item">My&nbsp;Decks</span>
        <span id="create-link" class="nav-item">Upload&nbsp;a&nbsp;New&nbsp;Deck</span>
    </span>
</nav>
<form id="manage-link-data-sender" action="/my-decks" method="POST">
    <input type="hidden" id="manage-link-key-input" name="key" value=""> <!-- Value will be filled in by JavaScript -->
</form>
<main>
    <header>
        <h1><?=
            /** @var string $layout_title Title of the webpage, initialized in the specific controller */
            $layout_title
        ?></h1>
    </header>
    <article>
        <?php require self::VIEWS_DIRECTORY.'/'.array_shift(self::$views).'.phtml'; ?>
    </article>
</main>
<?php foreach (self::$jsFiles as $jsFile) : ?>
    <script type="text/javascript" src="/public/js/<?= $jsFile ?>.js"></script>
<?php endforeach ?>
</body>
</html>

