<section>
    <p>
        This is a list of Anki packages registered in our database, that were created with the editing key saved in your
        <a href="/account">account setting</a> or that you entered in the form below.
    </p>
</section>
<section>
    <p>
        Are you looking for a package created with a different editing key? Enter the key in the form below:
    </p>
    <form id="manage-form" method="post">
        <input type="password" name="key" id="key-input" maxlength="31" placeholder="Enter your unsaved editing key" required/>
        <input id="submit-button" type="submit" value="Enter"/>
        <button id="reset-button">Reload Saved Key</button>
    </form>
</section>
<hr />
<section>
    <p>Use the icons to modify any of the deck:</p>
    <ul>
        <li>
            <img src="img/icons/download.png" alt="Download current version" class="icon" /> &minus; View the download page for the Anki deck.
        </li>
        <li>
            <img src="img/icons/upload.png" alt="Upload new version" class="icon" /> &minus; Upload an update of the Anki deck.
        </li>
        <li>
            <img src="img/icons/edit.png" alt="Edit metadata" class="icon" /> &minus; Edit name, author, description, editing key or protection of the Anki deck.
        </li>
        <li>
            <img src="img/icons/delete.png" alt="Delete" class="icon" /> &minus; Permanently delete the Anki deck from this service.
        </li>
    </ul>
</section>
<section>
    <?php if (empty($manage_packages)) : ?>
        <p class="no-results"><strong>No packages created with the editing key you provided found.</strong></p>
    <?php else : ?>
        <table class="wide-table striped-table">
            <tr>
                <th class="txt-l">Deck name</th>
                <th>Version number</th>
                <th>Last updated at</th>
                <th colspan="4">Action</th>
            </tr>
            <?php foreach ($manage_packages as $package) : ?>
                <tr>
                    <td class="txt-l"><?= $package['filename'] ?></td>
                    <td><?= $package['version'] ?></td>
                    <td><?= $package['updated_at'] ?></td>
                    <td class="icon-wrapper"><img src="img/icons/download.png" alt="Download current version" class="clickable-icon icon shadow-green" data-href="/deck/<?= $package['package_id'].(($package['access_key']) ? '?key='.$package['access_key'] : '') ?>"/></td>
                    <td class="icon-wrapper"><img src="img/icons/upload.png" alt="Upload new version" class="clickable-icon icon shadow-blue" data-href="/upload/<?= $package['package_id'] ?>"/></td>
                    <td class="icon-wrapper"><img src="img/icons/edit.png" alt="Edit metadata" class="clickable-icon icon shadow-yellow" data-href="/edit/<?= $package['package_id'] ?>"/></td>
                    <td class="icon-wrapper"><img src="img/icons/delete.png" alt="Delete" class="clickable-icon icon shadow-red" data-href="/delete/<?= $package['package_id'] ?>"/></td>
                </tr>
            <?php endforeach ?>
        </table>
        <form id="deck-modification-link-data-sender" action="" method="POST"> <!-- Action will be filled in by JavaScript -->
            <input type="hidden" id="deck-modification-link-key-input" name="key" value="<?= $manage_latestKey ?>">
        </form>
    <?php endif ?>
</section>

