<p>Toto je graf pseudo-unikátních uživatelů za posledních 30 dní.</p>
<p>
    Někteří uživatelé AnkiDroidu (mobilní klient pro Anki) a uživatelé AnkiWebu nejsou v těchto statistikách zahrnuti.
    To je kvůli nemožnosti kontrolovat aktualizace z těchto plaforem. Tohle by snad mohlo být časem opraveno, alespoň
    pro AnkiDroid (můžeš popostrčit vývojáře k práci na tomto komentováním
    na <a href="https://github.com/ankidroid/Anki-Android/issues/6669">příslušeném issue na GitHub)</a>.
</p>
<details>
    <summary>Jak jsou tyto statistiky počítány?</summary>
    <p>
        Pokaždé, když někdo otevře okno s popiskem Anki balíčku obsahujícím kód autoupdateru, Anki klient pošle
        HTTP požadavek na naše servery pro kontrolu, zda není k dispozici nová verze balíčeku. Odpovědí na tento
        požadavek je text jako "Používáš nejnovější verzi tohoto Anki balíčku."
    </p>
    <p>
        Každý požadavek na kontrolu aktualizací také zaznamená uživatelovu IP adresu do zabezpečeného textového souboru.
        IP adresa je ukládána ve formě hashe, což znemaná že nemůže být převedena zpět na IP adresu a ukládaný hash
        slouží pouze jako dočasný unikátní identifikátor.
    </p>
    <p>
        Každých 24 hodin jsou logy z předchozího dne agregovány do jednoho čísla pro každý balíček – počet unikátních
        IP adres, které byly za předchozí den zaznamenány. Toto číslo je uloženo v databázi (a později může být využito
        k vygenrování grafu jako toho, který vidíš níže) a seznam hashů IP adres je trvale vymazán. To znamená, že
        pouze hashe zaznamenané během současného a předcházejícího dne jsou ukládány a IP adresy uživatelů nejsou nikdy
        ukládány jako prostý text.
    </p>
    <p>
        Nevýhoda tohoto postupu je neschopnost odlišit uživatele jako lidi a namísto toho jejich odlišování pouze IP adresy.
        To znamená:
    </p>
    <ul>
        <li>
            Pokud jeden uživatel otevře tvůj Anki balíček dvakrát během jednoho dne, jednou na jejich domovské Wi-Fi síti
            a jednou zatímco využívá svá mobilní data, bude zaznamenán jako dva unikátní uživatelé, namísto jednoho.
        </li>
        <li>
            Pokud vícero uživatelů otevře tvůj Anki balíček zatímco jsou připojeni ze stejné Wi-Fi sítě, budou všichni
            zaznamenaní jako jediný uživatel.
        </li>
    </ul>
    <p>Drž proto prosím v paměti, že statistiky využívání jsou pouze přibližné.</p>
</details>

<div style="border: 1px solid black; margin: 1em 0;" class="wide-table">
    <?= $stats_graphSvg ?>
</div>

<h2>Celá historie statitiky využívání</h2>
<p>
    Celohistorické statistiky jsou k dispozici ke stažení ve formátu CSV.
    Stažený soubor můžeš naimportovat do tabulkového software jak je
    <a href="https://www.libreoffice.org/download/download-libreoffice/" target="_blank">LibreOffice Calc</a>
    nebo Microsoft Excel a nechat si graf vygenerovat v něm.
</p>
<form action="/stats/<?= $stats_packageId ?>/full" method="post">
    <input type="hidden" name="key" value="<?= $stats_key ?>"/>
    <input type="submit" style="display: block; background-color:cornflowerblue; font-size: x-large;"
           value="Stáhnout statistiky"/>
</form>

