<p>These are the terms of our service. We tried to keep them as humanly-readable and brief as possible.</p>

<h2>Terms for Anki Package Creators</h2>
<ol>
    <li>
        Any file you upload to our service (private or public) must not contain any materials bound by
        copyright, unless you have all the licences necessary for distribution of such materials.
    </li>
    <li>
        Any file you upload to our service must not contain any materials that might be considered illegal in
        western countries. If you have doubts, send an e-mail to <code>jan [dot] stech [at] posteo [dot] net</code>.
    </li>
    <li>
        We reserve the right to remove any of your content from our service or to shut down the service without prior
        notice.
        <br><small>
            (Don't worry, it will almost certainly not happen, we just want to play it safe.)
        </small>
    </li>
    <li>
        We reserve the right to host the files you upload to our service on any server we choose, even if it's not ours.
        <br><small>
            (This means that if we run out of storage space to store you Anki packages, we might upload them to service
            such as OneDrive or Discord to save space. Unlikely that this will be needed anytime soon.)
        </small>
    </li>
    <li>
        You have the right to remove any information created in our service by you for any reason by deleting any of
        your uploaded Anki decks.
    </li>
</ol>

<h2>Terms for Anki Package Users</h2>
<ol>
    <li>
        You are not permitted to download Anki packages from our service with the sole purpose of overloading our
        infrastructure.
    </li>
    <li>
        Whenever your Anki client sends a ping to our service to check if an update for your deck is available, we
        reserve the right to log your IP address for usage statistics. This IP address will be deleted from our servers
        after 48 hours at most, when the IP addresses will be aggregated together into one numbers – unique users of the
        Anki deck per day.
    </li>
    <li>
        We reserve to block any IP address from accessing our service for any reason.
        <br><small>
            (Don't worry, it will almost certainly not happen, we just want to play it safe.)
        </small>
    </li>
</ol>

