<p>Toto jsou naše podmínky služby. Pokusili jsme se je udělat tak lidsky-čitelné a krátké, jak jen bylo možné.</p>

<h2>Podmínky pro tvůrce Anki balíčků</h2>
<ol>
    <li>
        Jakýkoli soubor který nahraješ do naší služby (soukromé nebo veřejné) nestmí obsahovat materiály
        chráněné autorským právem, pokud nemáš veškeré licence nutné pro distribuci takových materiálů.
    </li>
    <li>
        Jakýkoli soubor který nahraješ do naší služby nesmí obsahovat jakékoli materiály, které mohou být povařovány
        za nelegální v jurisdikci České republiky. Pokud si nejsi jistý, zašli e-mail s dotazem
        na <code>shadymedic [at] posteo [dot] cz</code>.
    </li>
    <li>
        Vyhrazujeme si právo odebrat jakýkoli tvůj obsah z naší služby nebo ukončit provoz služby bez předchozího varování.
        <br><small>
            (Žádný strach, to se skoro určitě nestane, jen jsme raději opatrní.)
        </small>
    </li>
    <li>
        Vyhrazujeme si právo hostovat soubory, které nahraješ v cloudových úložištích třetích stran naší volby.
        <br><small>
            (Toto znamená, že pokud nám dojde místo na našich serverech, můžeme tvé Anki balíčky nahrát do jiného cloudového úložiště
            a spouštět jejich stahování z něj. Toto se ale zřejmě ještě dlouho nestane.)
        </small>
    </li>
    <li>
        Máš právo odebrat jakoukoli informaci, kterou jsi vytvořil/a v naší službě, z jakéhokoli důvodu a to odstraněním jakéhokoli
        tebou nahraného Anki balíčku.
    </li>
</ol>

<h2>Podmínky pro uživatele Anki balíčků</h2>
<ol>
    <li>
        Nemáš dovoleno stahovat Anki balíčky z naší služby s výhradním cílem přetížení naší infrastruktury.
    </li>
    <li>
        Kdykoli tvůj Anki klient pošle požadavek na naše servery, aby zkontroloval dostupnost aktualizací pro stažený Anki
        balíček, vyhrazujeme si právo zaznamenat tvojí IP adresu v zahashované (zašifrované a zároveň nedešifrovatelné) formě
        za účelem počítání statistik využívání jednotlivých balíčků. Tento hash IP adresy bude z našich serverů nejpozději
        po 48 hodinách odstraněn, během procesu agregace hashů do jednoho čísla – celkového počtu unikátních uživatelů (IP adres)
        využívajících daný balíček za daný den.
    </li>
    <li>
        Vyhrazujeme si právo zablokovat jakékoli IP adrese přístup k naším službám z jakéhokoli důvodu.
        <br><small>
            (Žádný strach, to se skoro určitě nestane, jenom chceme být opatrní.)
        </small>
    </li>
</ol>

