<p>Na tuto stránku jsi se dostal/a, protože jsi klikl na stav aktuálnosti balíčku, u nějž používáš nejnovější verzi.</p>
<p>Jakmile bude k dispozici nějaká aktualizace, budeš na její stránku ke stažení odsud přesměrován/a.</p>
<p>Pokud chceš tento balíček s někým sdílet, jenom jim pošli následující odkaz:<br>
    <code style="white-space: normal; background-color: #ddd; color: #222; padding: 4px;"><?= $uptodate_downloadLink ?></code>
</p>

