<p>You got to this webpage, because you clicked the update status of a deck that is currently up-to-date.</p>
<p>Once an update is available, you'll be redirected to its download page from here.</p>
<p>If you want to share this Anki deck with someone, just send them the following link:<br>
    <code style="white-space: normal; background-color: #ddd; color: #222; padding: 4px;"><?= $uptodate_downloadLink ?></code>
</p>

