<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anki Package Update Checker</title>
</head>
<body>
<header>
    <h1>Error 410</h1>
    <h2>Gone</h2>
</header>
<article>
    <p>Vyžádaný zdroj byl z této služby trvale odstraněn a není dostupná žádná přesmerovávací adresa.</p>
</article>
</body>
</html>
