<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anki Package Update Checker</title>
</head>
<body>
<header>
    <h1>Error 500</h1>
    <h2>Internal Server Error</h2>
</header>
<article>
    <p>Server neočekávatelně selhal zatímco se pokoušel zpracovat Váš požadavek.</p>
    <p>Zkuste to prosím znovu později a pokud chyba přetrvá, <a href="mailto:shadymedic@posteo.cz">kontaktujte správce webu</a>.</p>
</article>
</body>
</html>
