<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Anki Package Update Checker</title>
</head>
<body>
<header>
    <h1>Error 500</h1>
    <h2>Internal Server Error</h2>
</header>
<article>
    <p>The server encountered an unexpected error while trying to process your request.</p>
    <p>Please, try again later and if the issue persists, <a href="mailto:jan.stech@posteo.net">contact the webmaster</a>.</p>
</article>
</body>
</html>